language: java
jdk:
  - openjdk8
  - openjdk11
install:
 - mvn -version; docker version
script:
 - mvn -B formatter:validate impsort:check
 - mvn -B verify -DskipTests -Djboss.dist=foo
cache:
 directories:
  - $HOME/.m2